# Site settings
title: Apollo Software
email: email
domain: apollovision.github.io
#description: > 
# this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://apollovision.github.io # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: apollovision
twitter_username: ApolloVisionNet
github_username:  apollovision


# Build settings
markdown: kramdown
